/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface BettingDAOInterface extends Interface {
    getFunction(nameOrSignature: "adminCloseMarket" | "adminOpenMarket" | "betting" | "executeProposal" | "finalizeProposal" | "getProposal" | "hasVoted" | "nextProposalId" | "owner" | "proposals" | "proposeSetCommission" | "proposeSettleMarket" | "proposeWithdrawFees" | "quorumBps" | "renounceOwnership" | "setQuorum" | "setVotingDuration" | "token" | "transferOwnership" | "vote" | "votingDuration"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "OwnershipTransferred" | "ProposalCreated" | "ProposalExecuted" | "ProposalFinalized" | "QuorumUpdated" | "VoteCast" | "VotingDurationUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'adminCloseMarket', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'adminOpenMarket', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'betting', values?: undefined): string;
encodeFunctionData(functionFragment: 'executeProposal', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'finalizeProposal', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getProposal', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'hasVoted', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'nextProposalId', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'proposals', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'proposeSetCommission', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'proposeSettleMarket', values: [BigNumberish, string, string]): string;
encodeFunctionData(functionFragment: 'proposeWithdrawFees', values: [AddressLike, string]): string;
encodeFunctionData(functionFragment: 'quorumBps', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'setQuorum', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setVotingDuration', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'token', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'vote', values: [BigNumberish, boolean]): string;
encodeFunctionData(functionFragment: 'votingDuration', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'adminCloseMarket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'adminOpenMarket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'betting', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'executeProposal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'finalizeProposal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getProposal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasVoted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextProposalId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proposals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proposeSetCommission', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proposeSettleMarket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proposeWithdrawFees', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'quorumBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setQuorum', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setVotingDuration', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'token', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'vote', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'votingDuration', data: BytesLike): Result;
  }

  
    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProposalCreatedEvent {
      export type InputTuple = [id: BigNumberish, proposalType: BigNumberish, proposer: AddressLike, description: string, deadline: BigNumberish];
      export type OutputTuple = [id: bigint, proposalType: bigint, proposer: string, description: string, deadline: bigint];
      export interface OutputObject {id: bigint, proposalType: bigint, proposer: string, description: string, deadline: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProposalExecutedEvent {
      export type InputTuple = [id: BigNumberish, proposalType: BigNumberish];
      export type OutputTuple = [id: bigint, proposalType: bigint];
      export interface OutputObject {id: bigint, proposalType: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProposalFinalizedEvent {
      export type InputTuple = [id: BigNumberish, state: BigNumberish];
      export type OutputTuple = [id: bigint, state: bigint];
      export interface OutputObject {id: bigint, state: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace QuorumUpdatedEvent {
      export type InputTuple = [oldBps: BigNumberish, newBps: BigNumberish];
      export type OutputTuple = [oldBps: bigint, newBps: bigint];
      export interface OutputObject {oldBps: bigint, newBps: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VoteCastEvent {
      export type InputTuple = [proposalId: BigNumberish, voter: AddressLike, support: boolean, weight: BigNumberish];
      export type OutputTuple = [proposalId: bigint, voter: string, support: boolean, weight: bigint];
      export interface OutputObject {proposalId: bigint, voter: string, support: boolean, weight: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VotingDurationUpdatedEvent {
      export type InputTuple = [oldDuration: BigNumberish, newDuration: BigNumberish];
      export type OutputTuple = [oldDuration: bigint, newDuration: bigint];
      export interface OutputObject {oldDuration: bigint, newDuration: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface BettingDAO extends BaseContract {
    
    connect(runner?: ContractRunner | null): BettingDAO;
    waitForDeployment(): Promise<this>;

    interface: BettingDAOInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    adminCloseMarket: TypedContractMethod<
      [marketId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    adminOpenMarket: TypedContractMethod<
      [marketType: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    betting: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    executeProposal: TypedContractMethod<
      [proposalId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    finalizeProposal: TypedContractMethod<
      [proposalId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getProposal: TypedContractMethod<
      [id: BigNumberish, ],
      [[bigint, bigint, string, string, bigint, bigint, bigint] & {proposalType: bigint, state: bigint, proposer: string, description: string, votingDeadline: bigint, votesFor: bigint, votesAgainst: bigint }],
      'view'
    >
    

    
    hasVoted: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    nextProposalId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    proposals: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint, bigint, string, string, bigint, bigint, bigint, bigint, string] & {id: bigint, proposalType: bigint, state: bigint, proposer: string, description: string, votingDeadline: bigint, snapshotBlock: bigint, votesFor: bigint, votesAgainst: bigint, params: string }],
      'view'
    >
    

    
    proposeSetCommission: TypedContractMethod<
      [newPct: BigNumberish, description: string, ],
      [bigint],
      'nonpayable'
    >
    

    
    proposeSettleMarket: TypedContractMethod<
      [marketId: BigNumberish, winningGuess: string, description: string, ],
      [bigint],
      'nonpayable'
    >
    

    
    proposeWithdrawFees: TypedContractMethod<
      [to: AddressLike, description: string, ],
      [bigint],
      'nonpayable'
    >
    

    
    quorumBps: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setQuorum: TypedContractMethod<
      [newBps: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setVotingDuration: TypedContractMethod<
      [newDuration: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    token: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    vote: TypedContractMethod<
      [proposalId: BigNumberish, support: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    votingDuration: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'adminCloseMarket'): TypedContractMethod<
      [marketId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'adminOpenMarket'): TypedContractMethod<
      [marketType: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'betting'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'executeProposal'): TypedContractMethod<
      [proposalId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'finalizeProposal'): TypedContractMethod<
      [proposalId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getProposal'): TypedContractMethod<
      [id: BigNumberish, ],
      [[bigint, bigint, string, string, bigint, bigint, bigint] & {proposalType: bigint, state: bigint, proposer: string, description: string, votingDeadline: bigint, votesFor: bigint, votesAgainst: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'hasVoted'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'nextProposalId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'proposals'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint, bigint, string, string, bigint, bigint, bigint, bigint, string] & {id: bigint, proposalType: bigint, state: bigint, proposer: string, description: string, votingDeadline: bigint, snapshotBlock: bigint, votesFor: bigint, votesAgainst: bigint, params: string }],
      'view'
    >;
getFunction(nameOrSignature: 'proposeSetCommission'): TypedContractMethod<
      [newPct: BigNumberish, description: string, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'proposeSettleMarket'): TypedContractMethod<
      [marketId: BigNumberish, winningGuess: string, description: string, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'proposeWithdrawFees'): TypedContractMethod<
      [to: AddressLike, description: string, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'quorumBps'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setQuorum'): TypedContractMethod<
      [newBps: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setVotingDuration'): TypedContractMethod<
      [newDuration: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'token'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'vote'): TypedContractMethod<
      [proposalId: BigNumberish, support: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'votingDuration'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'ProposalCreated'): TypedContractEvent<ProposalCreatedEvent.InputTuple, ProposalCreatedEvent.OutputTuple, ProposalCreatedEvent.OutputObject>;
getEvent(key: 'ProposalExecuted'): TypedContractEvent<ProposalExecutedEvent.InputTuple, ProposalExecutedEvent.OutputTuple, ProposalExecutedEvent.OutputObject>;
getEvent(key: 'ProposalFinalized'): TypedContractEvent<ProposalFinalizedEvent.InputTuple, ProposalFinalizedEvent.OutputTuple, ProposalFinalizedEvent.OutputObject>;
getEvent(key: 'QuorumUpdated'): TypedContractEvent<QuorumUpdatedEvent.InputTuple, QuorumUpdatedEvent.OutputTuple, QuorumUpdatedEvent.OutputObject>;
getEvent(key: 'VoteCast'): TypedContractEvent<VoteCastEvent.InputTuple, VoteCastEvent.OutputTuple, VoteCastEvent.OutputObject>;
getEvent(key: 'VotingDurationUpdated'): TypedContractEvent<VotingDurationUpdatedEvent.InputTuple, VotingDurationUpdatedEvent.OutputTuple, VotingDurationUpdatedEvent.OutputObject>;

    filters: {
      
      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'ProposalCreated(uint256,uint8,address,string,uint256)': TypedContractEvent<ProposalCreatedEvent.InputTuple, ProposalCreatedEvent.OutputTuple, ProposalCreatedEvent.OutputObject>;
      ProposalCreated: TypedContractEvent<ProposalCreatedEvent.InputTuple, ProposalCreatedEvent.OutputTuple, ProposalCreatedEvent.OutputObject>;
    

      'ProposalExecuted(uint256,uint8)': TypedContractEvent<ProposalExecutedEvent.InputTuple, ProposalExecutedEvent.OutputTuple, ProposalExecutedEvent.OutputObject>;
      ProposalExecuted: TypedContractEvent<ProposalExecutedEvent.InputTuple, ProposalExecutedEvent.OutputTuple, ProposalExecutedEvent.OutputObject>;
    

      'ProposalFinalized(uint256,uint8)': TypedContractEvent<ProposalFinalizedEvent.InputTuple, ProposalFinalizedEvent.OutputTuple, ProposalFinalizedEvent.OutputObject>;
      ProposalFinalized: TypedContractEvent<ProposalFinalizedEvent.InputTuple, ProposalFinalizedEvent.OutputTuple, ProposalFinalizedEvent.OutputObject>;
    

      'QuorumUpdated(uint256,uint256)': TypedContractEvent<QuorumUpdatedEvent.InputTuple, QuorumUpdatedEvent.OutputTuple, QuorumUpdatedEvent.OutputObject>;
      QuorumUpdated: TypedContractEvent<QuorumUpdatedEvent.InputTuple, QuorumUpdatedEvent.OutputTuple, QuorumUpdatedEvent.OutputObject>;
    

      'VoteCast(uint256,address,bool,uint256)': TypedContractEvent<VoteCastEvent.InputTuple, VoteCastEvent.OutputTuple, VoteCastEvent.OutputObject>;
      VoteCast: TypedContractEvent<VoteCastEvent.InputTuple, VoteCastEvent.OutputTuple, VoteCastEvent.OutputObject>;
    

      'VotingDurationUpdated(uint256,uint256)': TypedContractEvent<VotingDurationUpdatedEvent.InputTuple, VotingDurationUpdatedEvent.OutputTuple, VotingDurationUpdatedEvent.OutputObject>;
      VotingDurationUpdated: TypedContractEvent<VotingDurationUpdatedEvent.InputTuple, VotingDurationUpdatedEvent.OutputTuple, VotingDurationUpdatedEvent.OutputObject>;
    
    };
  }