/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface WorldCupBettingInterface extends Interface {
    getFunction(nameOrSignature: "BASIS_POINTS" | "MAX_COMMISSION" | "accumulatedFees" | "claimPrize" | "closeMarket" | "commissionPct" | "getBet" | "getMarketInfo" | "hasClaimed" | "nextMarketId" | "openMarket" | "owner" | "placeBet" | "renounceOwnership" | "setCommission" | "settleMarket" | "transferOwnership" | "withdrawFees"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "BetPlaced" | "CommissionUpdated" | "FeesWithdrawn" | "MarketClosed" | "MarketOpened" | "MarketSettled" | "OwnershipTransferred" | "PrizeClaimed"): EventFragment;

    encodeFunctionData(functionFragment: 'BASIS_POINTS', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_COMMISSION', values?: undefined): string;
encodeFunctionData(functionFragment: 'accumulatedFees', values?: undefined): string;
encodeFunctionData(functionFragment: 'claimPrize', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'closeMarket', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'commissionPct', values?: undefined): string;
encodeFunctionData(functionFragment: 'getBet', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'getMarketInfo', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'hasClaimed', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'nextMarketId', values?: undefined): string;
encodeFunctionData(functionFragment: 'openMarket', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'placeBet', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'setCommission', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'settleMarket', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'withdrawFees', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'BASIS_POINTS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_COMMISSION', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'accumulatedFees', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimPrize', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'closeMarket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'commissionPct', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBet', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMarketInfo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasClaimed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextMarketId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'openMarket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'placeBet', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setCommission', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'settleMarket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawFees', data: BytesLike): Result;
  }

  
    export namespace BetPlacedEvent {
      export type InputTuple = [marketId: BigNumberish, bettor: AddressLike, guess: string, amount: BigNumberish];
      export type OutputTuple = [marketId: bigint, bettor: string, guess: string, amount: bigint];
      export interface OutputObject {marketId: bigint, bettor: string, guess: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CommissionUpdatedEvent {
      export type InputTuple = [oldPct: BigNumberish, newPct: BigNumberish];
      export type OutputTuple = [oldPct: bigint, newPct: bigint];
      export interface OutputObject {oldPct: bigint, newPct: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FeesWithdrawnEvent {
      export type InputTuple = [to: AddressLike, amount: BigNumberish];
      export type OutputTuple = [to: string, amount: bigint];
      export interface OutputObject {to: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MarketClosedEvent {
      export type InputTuple = [marketId: BigNumberish];
      export type OutputTuple = [marketId: bigint];
      export interface OutputObject {marketId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MarketOpenedEvent {
      export type InputTuple = [marketId: BigNumberish, marketType: BigNumberish];
      export type OutputTuple = [marketId: bigint, marketType: bigint];
      export interface OutputObject {marketId: bigint, marketType: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MarketSettledEvent {
      export type InputTuple = [marketId: BigNumberish, winningGuess: string, winnerPool: BigNumberish, fee: BigNumberish];
      export type OutputTuple = [marketId: bigint, winningGuess: string, winnerPool: bigint, fee: bigint];
      export interface OutputObject {marketId: bigint, winningGuess: string, winnerPool: bigint, fee: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PrizeClaimedEvent {
      export type InputTuple = [marketId: BigNumberish, winner: AddressLike, prize: BigNumberish];
      export type OutputTuple = [marketId: bigint, winner: string, prize: bigint];
      export interface OutputObject {marketId: bigint, winner: string, prize: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface WorldCupBetting extends BaseContract {
    
    connect(runner?: ContractRunner | null): WorldCupBetting;
    waitForDeployment(): Promise<this>;

    interface: WorldCupBettingInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    BASIS_POINTS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_COMMISSION: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    accumulatedFees: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    claimPrize: TypedContractMethod<
      [marketId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    closeMarket: TypedContractMethod<
      [marketId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    commissionPct: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getBet: TypedContractMethod<
      [marketId: BigNumberish, bettor: AddressLike, ],
      [[string, bigint] & {guess: string, amount: bigint }],
      'view'
    >
    

    
    getMarketInfo: TypedContractMethod<
      [marketId: BigNumberish, ],
      [[bigint, bigint, string, bigint, bigint, bigint, bigint] & {marketType: bigint, state: bigint, winningGuess: string, totalPool: bigint, winnerPool: bigint, commission: bigint, betCount: bigint }],
      'view'
    >
    

    
    hasClaimed: TypedContractMethod<
      [marketId: BigNumberish, bettor: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    nextMarketId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    openMarket: TypedContractMethod<
      [marketType: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    placeBet: TypedContractMethod<
      [marketId: BigNumberish, guess: string, ],
      [void],
      'payable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setCommission: TypedContractMethod<
      [newPct: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    settleMarket: TypedContractMethod<
      [marketId: BigNumberish, winningGuess: string, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    withdrawFees: TypedContractMethod<
      [to: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'BASIS_POINTS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_COMMISSION'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'accumulatedFees'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'claimPrize'): TypedContractMethod<
      [marketId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'closeMarket'): TypedContractMethod<
      [marketId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'commissionPct'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getBet'): TypedContractMethod<
      [marketId: BigNumberish, bettor: AddressLike, ],
      [[string, bigint] & {guess: string, amount: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getMarketInfo'): TypedContractMethod<
      [marketId: BigNumberish, ],
      [[bigint, bigint, string, bigint, bigint, bigint, bigint] & {marketType: bigint, state: bigint, winningGuess: string, totalPool: bigint, winnerPool: bigint, commission: bigint, betCount: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'hasClaimed'): TypedContractMethod<
      [marketId: BigNumberish, bettor: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'nextMarketId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'openMarket'): TypedContractMethod<
      [marketType: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'placeBet'): TypedContractMethod<
      [marketId: BigNumberish, guess: string, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setCommission'): TypedContractMethod<
      [newPct: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'settleMarket'): TypedContractMethod<
      [marketId: BigNumberish, winningGuess: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawFees'): TypedContractMethod<
      [to: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'BetPlaced'): TypedContractEvent<BetPlacedEvent.InputTuple, BetPlacedEvent.OutputTuple, BetPlacedEvent.OutputObject>;
getEvent(key: 'CommissionUpdated'): TypedContractEvent<CommissionUpdatedEvent.InputTuple, CommissionUpdatedEvent.OutputTuple, CommissionUpdatedEvent.OutputObject>;
getEvent(key: 'FeesWithdrawn'): TypedContractEvent<FeesWithdrawnEvent.InputTuple, FeesWithdrawnEvent.OutputTuple, FeesWithdrawnEvent.OutputObject>;
getEvent(key: 'MarketClosed'): TypedContractEvent<MarketClosedEvent.InputTuple, MarketClosedEvent.OutputTuple, MarketClosedEvent.OutputObject>;
getEvent(key: 'MarketOpened'): TypedContractEvent<MarketOpenedEvent.InputTuple, MarketOpenedEvent.OutputTuple, MarketOpenedEvent.OutputObject>;
getEvent(key: 'MarketSettled'): TypedContractEvent<MarketSettledEvent.InputTuple, MarketSettledEvent.OutputTuple, MarketSettledEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'PrizeClaimed'): TypedContractEvent<PrizeClaimedEvent.InputTuple, PrizeClaimedEvent.OutputTuple, PrizeClaimedEvent.OutputObject>;

    filters: {
      
      'BetPlaced(uint256,address,string,uint256)': TypedContractEvent<BetPlacedEvent.InputTuple, BetPlacedEvent.OutputTuple, BetPlacedEvent.OutputObject>;
      BetPlaced: TypedContractEvent<BetPlacedEvent.InputTuple, BetPlacedEvent.OutputTuple, BetPlacedEvent.OutputObject>;
    

      'CommissionUpdated(uint256,uint256)': TypedContractEvent<CommissionUpdatedEvent.InputTuple, CommissionUpdatedEvent.OutputTuple, CommissionUpdatedEvent.OutputObject>;
      CommissionUpdated: TypedContractEvent<CommissionUpdatedEvent.InputTuple, CommissionUpdatedEvent.OutputTuple, CommissionUpdatedEvent.OutputObject>;
    

      'FeesWithdrawn(address,uint256)': TypedContractEvent<FeesWithdrawnEvent.InputTuple, FeesWithdrawnEvent.OutputTuple, FeesWithdrawnEvent.OutputObject>;
      FeesWithdrawn: TypedContractEvent<FeesWithdrawnEvent.InputTuple, FeesWithdrawnEvent.OutputTuple, FeesWithdrawnEvent.OutputObject>;
    

      'MarketClosed(uint256)': TypedContractEvent<MarketClosedEvent.InputTuple, MarketClosedEvent.OutputTuple, MarketClosedEvent.OutputObject>;
      MarketClosed: TypedContractEvent<MarketClosedEvent.InputTuple, MarketClosedEvent.OutputTuple, MarketClosedEvent.OutputObject>;
    

      'MarketOpened(uint256,uint8)': TypedContractEvent<MarketOpenedEvent.InputTuple, MarketOpenedEvent.OutputTuple, MarketOpenedEvent.OutputObject>;
      MarketOpened: TypedContractEvent<MarketOpenedEvent.InputTuple, MarketOpenedEvent.OutputTuple, MarketOpenedEvent.OutputObject>;
    

      'MarketSettled(uint256,string,uint256,uint256)': TypedContractEvent<MarketSettledEvent.InputTuple, MarketSettledEvent.OutputTuple, MarketSettledEvent.OutputObject>;
      MarketSettled: TypedContractEvent<MarketSettledEvent.InputTuple, MarketSettledEvent.OutputTuple, MarketSettledEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'PrizeClaimed(uint256,address,uint256)': TypedContractEvent<PrizeClaimedEvent.InputTuple, PrizeClaimedEvent.OutputTuple, PrizeClaimedEvent.OutputObject>;
      PrizeClaimed: TypedContractEvent<PrizeClaimedEvent.InputTuple, PrizeClaimedEvent.OutputTuple, PrizeClaimedEvent.OutputObject>;
    
    };
  }